### ISSUE TITLE
Integrate dach

### ISSUE THREAD

**Issue by MrChico** [makerdao/dss-deploy#11]
I would like to modify the Dai ds-token that is currently included in this project to be able to support token transfers by signed messages. If we are upgrading the dai token contract anyway, this is an excellent opportunity to add this functionality which allows people to transact dai without needing ether to pay for gas. A sketch implementation is here https://github.com/MrChico/tokens/blob/master/src/dach.sol

**Comment by michaelelliot** [comment]
I would love to see this feature in the Dai token.

**Comment by michaelelliot** [comment]
@MrChico Would a `deadline` param be a useful feature so that signatures can expire?

**Comment by gbalabasquer** [comment]
I think @rainbreak is preparing a simpler erc20 contract for DAI. I'm on favor to add the offchain transfers to it.

**Comment by rainbreak** [comment]
Don't users just need to `approve` the dach contract to enable this? Or are you suggesting that it should be enabled by default?

**Comment by gbalabasquer** [comment]
I think he is meaning to add the offchain transfers directly to dai erc20 the token

**Comment by MrChico** [comment]
Yes, I'm suggesting to enable it by default, granting it authorized access to `transferFrom`, or something equivalent. In ERC777 terminology, `dach` would be a `defaultOperator`.

And yes, a timeout is an interesting thing to consider. Another way to invalidate an old cheque is to "overwrite" it by having another submitted with the same nonce.
