### ISSUE TITLE
Use actual collateral token contracts

### ISSUE THREAD

**Issue by jparklev** [makerdao/dss-deploy#12]
Right now the deploy scripts use normal `ds-token` contracts for every collateral type. For example:
https://github.com/makerdao/dss-deploy/blob/fe76c436349f8f6fc110553d0583d1c214fbcaf2/bin/deploy-dgx#L12
However, in the wild these collateral types have their own unique token contracts and can have their own idiosyncrasies with respect to how we interact with them (eg DGX has 9 decimal places). Because these scripts are used extensively in testing, a good move might be to go ahead and add in the real contracts. Or is there some additional context i'm missing here?

Edit: on second thought, a token contract we instantiate with different decimal places might be enough?

@levity @gbalabasquer

**Comment by gbalabasquer** [comment]
We are going to include the real adapters and more similar tokens to the real ones in `dss-deploy` soon

**Comment by levity** [comment]
@jparklev great point though about needing to support token contracts with different decimal place settings. i overlooked that in the first cut
