### ISSUE TITLE
Does `mat` belong here or in the pit?

### ISSUE THREAD

**Issue by levity** [makerdao/dss-deploy#13]
Maybe the storage of `mat` can be moved to the Pit, just like `spot` and `line`?

https://github.com/makerdao/dss-deploy/blob/fe76c436349f8f6fc110553d0583d1c214fbcaf2/src/poke.sol#L20

**Comment by gbalabasquer** [comment]
@rainbreak what was the reasoning of having `mat` coming in the `spot` value?

**Comment by rainbreak** [comment]
The interpretation of the `spot` is "maximum dai allowed per collateral", which is the only price feed that the core cares about. The `mat` used to be in the core, but was moved out for simplicity and to avoid using division (which causes precision loss).

One thing I would consider is moving the spotter into dss, where it would be a component similar to the collateral adapters, defining the boundaries of the system.

**Comment by gbalabasquer** [comment]
Sounds good to me, after we define the latest `dss` changes, I could move the spotter.
