### ISSUE TITLE
Set variables using "file" in dss contracts

### ISSUE THREAD

**Issue by kctam** [makerdao/dss-deploy#23]
Hi,
I am doing a simulation of dss on dapp testnet, using dss-deploy code. Everything looks good (as I can join COL1-A and lock COL1-A using frob). But I try to modify variables like Line, ilks[ilk].line in Vat or ilks[ilk].duty in Jug for demo purpose. I cannot use "seth send" command on file() and seems it's due to authority, as I see wards[default]=0. Is there a way to either set that wards[default] to 1, or is there other way to set these variables? 
Thanks in advance.

**Comment by asymmetric** [comment]
@kctam `wards` is set by `rely` methods, as you can see [here](https://github.com/makerdao/dss-deploy/blob/5a828e2eac5dcce1deddca89270492e122430e76/src/DssDeploy.sol#L46).

Please use the `#dev` channel on https://chat.makerdao.com for questions, rather than GitHub issues.

Thanks!
