### ISSUE TITLE
DssDeploy.t.base.sol: ProxyActions.deny bug

### ISSUE THREAD

**Issue by yaronvel** [makerdao/dss-deploy#59]
In line [97](https://github.com/makerdao/dss-deploy/blob/master/src/DssDeploy.t.base.sol#L97):
```
 bytes memory fax = abi.encodeWithSignature("rely(address,address)", from, to);
```
should be `deny` instead of `rely`.

**Comment by gbalabasquer** [comment]
Thank you, we will get it fixed soon.

**Comment by gbalabasquer** [comment]
Fixed: https://github.com/makerdao/dss-deploy/commit/cc14f7d306de88cfc6e71ef602f549193d642552
